export const DUMMY_MENUS1 = [
   {
      id: 'dashboard',
      mn_name: 'Dashboard',
      mn_link: '/dashboard',
      mn_icon: 'LayoutDashboard',
      mn_acl: 'lvl_dash',
      mn_parentid: '',
      mn_order: '1',
      mn_source: 'main',
      mn_source_react: 'main',
      mn_breadcrumb: 'Dashboard',
      child: [],
      active: false,
   },
   {
      id: 'user',
      mn_name: 'User',
      mn_link: '#',
      mn_icon: 'Users',
      mn_acl: 'lvl_user',
      mn_parentid: '',
      mn_order: '2',
      mn_source: 'main',
      mn_source_react: 'main',
      mn_breadcrumb: 'User',
      active: false,
      child: [
         {
            id: 'user-list',
            mn_name: 'User List',
            mn_link: '/dashboard/users',
            mn_icon: 'UserRound',
            mn_acl: 'lvl_user_list',
            mn_parentid: 'user',
            mn_order: '1',
            mn_source: 'main',
            mn_source_react: 'main',
            mn_breadcrumb: 'User > User List',
            child: [],
            active: false,
         },
         {
            id: 'user-role',
            mn_name: 'User Role',
            mn_link: '/dashboard/users/role',
            mn_icon: 'ShieldCheck',
            mn_acl: 'lvl_user_role',
            mn_parentid: 'user',
            mn_order: '2',
            mn_source: 'main',
            mn_source_react: 'main',
            mn_breadcrumb: 'User > User Role',
            child: [],
            active: false,
         },
      ],
   },
]

export const DUMMY_MENUS = [
   {
      id: 'dashboard',
      mn_name: 'Dashboard',
      mn_link: '/dashboard',
      mn_icon: 'LayoutDashboard',
      mn_acl: 'lvl_dash',
      mn_parentid: '',
      mn_order: '1',
      mn_source: 'main',
      mn_source_react: 'main',
      mn_breadcrumb: 'Dashboard',
      child: [],
      active: false,
   },
   {
      id: 'shipments',
      mn_name: 'Shipments',
      mn_link: '/dashboard/shipments',
      mn_icon: 'Package',
      mn_acl: 'lvl_shipment',
      mn_parentid: '',
      mn_order: '2',
      mn_source: 'main',
      mn_source_react: 'main',
      mn_breadcrumb: 'Shipments',
      active: false,
      child: [],
   },
   {
      id: 'customers',
      mn_name: 'Customers',
      mn_link: '/dashboard/customers',
      mn_icon: 'Building2',
      mn_acl: 'lvl_customer',
      mn_parentid: '',
      mn_order: '3',
      mn_source: 'main',
      mn_source_react: 'main',
      mn_breadcrumb: 'Customers',
      active: false,
      child: [],
   },
   {
      id: 'vehicles',
      mn_name: 'Fleet',
      mn_link: '/dashboard/vehicles',
      mn_icon: 'Truck',
      mn_acl: 'lvl_vehicle',
      mn_parentid: '',
      mn_order: '4',
      mn_source: 'main',
      mn_source_react: 'main',
      mn_breadcrumb: 'Fleet',
      active: false,
      child: [],
   },
   {
      id: 'user',
      mn_name: 'User Management',
      mn_link: '/dashboard/users',
      mn_icon: 'Users',
      mn_acl: 'lvl_user',
      mn_parentid: '',
      mn_order: '5',
      mn_source: 'main',
      mn_source_react: 'main',
      mn_breadcrumb: 'User',
      active: false,
      child: [],
   },
]
